# Generated by Django 4.2.23 on 2026-03-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('in_preparation', 'In Preparation')], default='published', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
    ]
