# Generated by Django 4.2.23 on 2026-03-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, to='portfolio.skill'),
        ),
    ]
