# Generated by Django 4.2.23 on 2026-03-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_experience_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
