# Generated by Django 4.2.23 on 2026-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_publication_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
