# Generated by Django 4.2.23 on 2026-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_publication_venue_alter_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='portfolio.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.URLField(blank=True, default=''),
        ),
    ]
